{{/*
  backend-service.yaml
  Helm template for Backend Kubernetes Service
  All values are configurable via values.yaml
*/}}
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - name: "backend"
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  selector:
    app: backend
