name: Build and Push Multi-Arch Docker Images

on:
  push:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push backend
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile.backend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: guestros/localgpt-backend:latest

    - name: Build and push frontend
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile.frontend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: guestros/localgpt-frontend:latest

    - name: Build and push rag-api
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile.rag-api
        platforms: linux/amd64,linux/arm64
        push: true
        tags: guestros/localgpt-rag-api:latest
